# Understanding Feature Distributions — Iris Dataset

Before training any ML model, we analyze feature distributions to understand the data.

**Topics covered:**
- Extracting feature matrix as NumPy array
- Computing mean, median, std, variance per feature
- Identifying highest-variability feature and its ML significance
- Reshaping a feature to `(n, 1)` and why ML models require this

In [1]:
import numpy as np
from sklearn.datasets import load_iris

# Load dataset
iris = load_iris()

# --- Task 1: Extract feature matrix as NumPy array ---
X = iris.data          # shape: (150, 4)
feature_names = iris.feature_names

print("Feature names:", feature_names)
print("Shape of X   :", X.shape)
print("Type         :", type(X))
print("\nFirst 5 rows:\n", X[:5])

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Shape of X   : (150, 4)
Type         : <class 'numpy.ndarray'>

First 5 rows:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [2]:
# --- Task 2: Compute statistics for each feature ---

print(f"{'Statistic':<12}", end="")
for name in feature_names:
    print(f"{name[:18]:<20}", end="")
print()
print("-" * 92)

stats = {
    "Mean"    : np.mean(X, axis=0),
    "Median"  : np.median(X, axis=0),
    "Std Dev" : np.std(X, axis=0),
    "Variance": np.var(X, axis=0),
}

for stat_name, values in stats.items():
    print(f"{stat_name:<12}", end="")
    for v in values:
        print(f"{v:<20.4f}", end="")
    print()

Statistic   sepal length (cm)   sepal width (cm)    petal length (cm)   petal width (cm)    
--------------------------------------------------------------------------------------------
Mean        5.8433              3.0573              3.7580              1.1993              
Median      5.8000              3.0000              4.3500              1.3000              
Std Dev     0.8253              0.4344              1.7594              0.7597              
Variance    0.6811              0.1887              3.0955              0.5771              


In [8]:
# --- Task 3: Identify feature with highest variability ---

variances = np.var(X, axis=0)
highest_idx = np.argmax(variances)
highest_feature = feature_names[highest_idx]

print("Variance per feature:")
for name, var in zip(feature_names, variances):
    #marker = "  <-- HIGHEST" if name == highest_feature else ""
    print(f"  {name:<30}: {var:.4f}{marker}")

print(f"\nFeature with highest variability: '{highest_feature}'")
print()


Variance per feature:
  sepal length (cm)             : 0.6811
  sepal width (cm)              : 0.1887
  petal length (cm)             : 3.0955
  petal width (cm)              : 0.5771

Feature with highest variability: 'petal length (cm)'



In [7]:
# --- Task 4: Reshape one feature to (n, 1) ---

# Extract petal length (column index 2) as a 1-D array
petal_length_1d = X[:, 2]
print("Original shape (1-D):", petal_length_1d.shape)   # (150,)

# Reshape to (n, 1)  — a 2-D column vector
petal_length_2d = petal_length_1d.reshape(-1, 1)         # -1 infers n automatically
print("Reshaped  (2-D)     :", petal_length_2d.shape)    # (150, 1)

print("\nFirst 5 values (1-D):", petal_length_1d[:5])
print("First 5 values (2-D):\n", petal_length_2d[:5])



Original shape (1-D): (150,)
Reshaped  (2-D)     : (150, 1)

First 5 values (1-D): [1.4 1.4 1.3 1.5 1.4]
First 5 values (2-D):
 [[1.4]
 [1.4]
 [1.3]
 [1.5]
 [1.4]]
